use bambam::model::builders;
use pyo3::prelude::*;
use routee_compass::app::{
    bindings::CompassAppBindings,
    compass::{CompassApp, CompassAppConfig, CompassAppError, CompassBuilderInventory},
};
use routee_compass_macros::pybindings;

// add BAMBAM extensions to RouteE Compass
inventory::submit! { builders::BUILDER_REGISTRATION }

/// a wrapper around CompassApp for running BAMBAM
#[pybindings]
pub struct BambamAppWrapper {
    pub app: CompassApp,
}

impl CompassAppBindings for BambamAppWrapper {
    /// creates a BAMBAM app instance from a configuration file.
    fn from_config_toml_string(
        config_string: String,
        original_file_path: String,
    ) -> Result<Self, CompassAppError>
    where
        Self: Sized,
    {
        // while effectively the same as routee-compass-py's lib.rs,
        // this will automatically pick up both routee-compass AND bambam builders
        // during compilation, adding the access modeling extensions.
        let builder = CompassBuilderInventory::new()?;
        let config = CompassAppConfig::from_str(
            &config_string,
            &original_file_path,
            config::FileFormat::Toml,
        )?;
        let app = CompassApp::new(&config, &builder)?;
        Ok(BambamAppWrapper { app })
    }
    fn app(&self) -> &CompassApp {
        &self.app
    }
}

/// Run the OMF Network data import operation using arguments deserialized from Python.
///
/// Accepts a dictionary, a Pydantic model (with `model_dump`), or a JSON string.
#[pyfunction]
fn run_omf_network(py: Python<'_>, args: &Bound<'_, PyAny>) -> PyResult<()> {
    let network_args: bambam_omf::app::OmfNetworkArgs =
        if let Ok(json_str) = args.extract::<String>() {
            serde_json::from_str(&json_str).map_err(|e| {
                PyErr::new::<pyo3::exceptions::PyValueError, _>(format!(
                    "failed to deserialize JSON string: {e}"
                ))
            })?
        } else if let Ok(dict) = args.call_method0("model_dump") {
            pythonize::depythonize(&dict).map_err(|e| {
                PyErr::new::<pyo3::exceptions::PyValueError, _>(format!(
                    "failed to deserialize Pydantic model: {e}"
                ))
            })?
        } else {
            pythonize::depythonize(args).map_err(|e| {
                PyErr::new::<pyo3::exceptions::PyValueError, _>(format!(
                    "failed to deserialize arguments: {e}"
                ))
            })?
        };

    py.detach(move || {
        network_args
            .run()
            .map_err(|e| PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(e.to_string()))
    })
}

/// Get the JSON Schema for OmfNetworkArgs generated by schemars.
#[pyfunction]
fn omf_network_schema() -> PyResult<String> {
    let schema = schemars::schema_for!(bambam_omf::app::OmfNetworkArgs);
    serde_json::to_string_pretty(&schema)
        .map_err(|e| PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(e.to_string()))
}

/// register bambam_py_api as a package in Python
#[pymodule]
fn bambam_py_api(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<BambamAppWrapper>()?;
    m.add_function(wrap_pyfunction!(run_omf_network, m)?)?;
    m.add_function(wrap_pyfunction!(omf_network_schema, m)?)?;
    Ok(())
}
