from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, field_validator

from nlr.bambam.bambam_py_api import omf_network_schema as _rust_omf_network_schema
from nlr.bambam.bambam_py_api import run_omf_network as _rust_run_omf_network

logger = logging.getLogger(__name__)


class OmfNetworkArgs(BaseModel):
    """Configuration arguments for the OMF Network import operation.

    Mirrors the Rust struct `bambam_omf::app::OmfNetworkArgs` and CLI command
    `bambam-omf network`.
    """

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        populate_by_name=True,
    )

    name: str = Field(
        ...,
        description="descriptive user-provided name for this import region.",
    )
    configuration_file: Union[str, Path] = Field(
        ...,
        description=(
            "configuration file defining how the network is imported and separated "
            "into mode-specific edge lists."
        ),
    )
    output_directory: Optional[Union[str, Path]] = Field(
        default=None,
        description=(
            "location on disk to write output files. if not provided, "
            "use the current working directory."
        ),
    )
    local_source: Optional[Union[str, Path]] = Field(
        default=None,
        description=(
            "use a stored raw data export from a previous run of OmfOperation::Network "
            "which is a JSON file containing a TransportationCollection."
        ),
    )
    store_raw: bool = Field(
        default=False,
        description="write the raw OMF dataset as a JSON blob to the output directory.",
    )
    omf_ids: bool = Field(
        default=False,
        description="write the list of segment and connector IDs for each edge created",
    )
    extent_file: Optional[Union[str, Path]] = Field(
        default=None,
        description="Optional WKT extent in json format. expects a json file with a single \"extent\" key",
    )

    @field_validator(
        "configuration_file",
        "output_directory",
        "local_source",
        "extent_file",
        mode="before",
    )
    @classmethod
    def _stringify_path(cls, v: Any) -> Any:
        if isinstance(v, Path):
            return str(v)
        return v

    def to_rust_dict(self) -> dict[str, Any]:
        """Export to a dictionary formatted for consumption by Rust via pythonize."""
        return self.model_dump(mode="json")

    def to_cli_args(self) -> list[str]:
        """Convert to CLI argument list suitable for invoking `bambam-omf network`."""
        args: list[str] = [
            "network",
            "--name",
            self.name,
            "--configuration-file",
            str(self.configuration_file),
        ]
        if self.output_directory is not None:
            args.extend(["--output-directory", str(self.output_directory)])
        if self.local_source is not None:
            args.extend(["--local-source", str(self.local_source)])
        if self.store_raw:
            args.append("--store-raw")
        if self.omf_ids:
            args.append("--omf-ids")
        if self.extent_file is not None:
            args.extend(["--extent-file", str(self.extent_file)])
        return args

    @classmethod
    def rust_json_schema(cls) -> dict[str, Any]:
        """Get the JSON schema directly from the compiled Rust library generated by schemars."""
        schema_str = _rust_omf_network_schema()
        return json.loads(schema_str)  # type: ignore[no-any-return]

    @classmethod
    def check_schema_parity(cls) -> bool:
        """Verify that Pydantic fields match Rust schemars properties and required fields."""
        rust_schema = cls.rust_json_schema()
        rust_props = rust_schema.get("properties", {})
        rust_required = set(rust_schema.get("required", []))

        py_schema = cls.model_json_schema()
        py_props = py_schema.get("properties", {})
        py_required = set(py_schema.get("required", []))

        props_match = set(rust_props.keys()) == set(py_props.keys())
        required_match = rust_required == py_required
        return props_match and required_match

    def run(self) -> None:
        """Run this OMF network operation in-process via compiled Rust bindings."""
        run_omf_network(self)


def run_omf_network(
    args: Optional[Union[OmfNetworkArgs, dict[str, Any]]] = None,
    *,
    name: Optional[str] = None,
    configuration_file: Optional[Union[str, Path]] = None,
    output_directory: Optional[Union[str, Path]] = None,
    local_source: Optional[Union[str, Path]] = None,
    store_raw: bool = False,
    omf_ids: bool = False,
    extent_file: Optional[Union[str, Path]] = None,
    **kwargs: Any,
) -> None:
    """Run the OMF network data import operation.

    Can be invoked by passing an `OmfNetworkArgs` instance, a dictionary of arguments,
    or keyword arguments matching the fields.

    Args:
        args: Optional pre-constructed `OmfNetworkArgs` or dictionary.
        name: User-provided name for this import region.
        configuration_file: Path to TOML configuration defining edge lists.
        output_directory: Optional output directory for generated files.
        local_source: Optional path to raw OMF dataset from a prior run.
        store_raw: Whether to write the raw OMF dataset as JSON to disk.
        omf_ids: Whether to export segment/connector ID mappings.
        extent_file: Optional WKT extent JSON file.
        **kwargs: Additional keyword arguments forwarded to `OmfNetworkArgs`.
    """
    if args is not None:
        if isinstance(args, OmfNetworkArgs):
            network_args = args
        elif isinstance(args, dict):
            network_args = OmfNetworkArgs(**args)
        else:
            raise TypeError(f"Expected OmfNetworkArgs or dict, got {type(args).__name__}")
    else:
        explicit_kwargs: dict[str, Any] = {}
        if name is not None:
            explicit_kwargs["name"] = name
        if configuration_file is not None:
            explicit_kwargs["configuration_file"] = configuration_file
        if output_directory is not None:
            explicit_kwargs["output_directory"] = output_directory
        if local_source is not None:
            explicit_kwargs["local_source"] = local_source
        if store_raw:
            explicit_kwargs["store_raw"] = store_raw
        if omf_ids:
            explicit_kwargs["omf_ids"] = omf_ids
        if extent_file is not None:
            explicit_kwargs["extent_file"] = extent_file
        explicit_kwargs.update(kwargs)
        network_args = OmfNetworkArgs(**explicit_kwargs)

    logger.info("Executing OMF network import for region '%s'...", network_args.name)
    _rust_run_omf_network(network_args.to_rust_dict())
